services:
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    volumes:
      - ./backend/:/app

  frontend:
    build: ./b3-ver/
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
  celery:
    build: ./backend/
    entrypoint: /app/entrypoint_celery.sh
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./backend/:/app